### ISSUE TITLE
Suggestion: Avro addon

### ISSUE THREAD

**Issue by deathstrikex** [MythicAngel/rokeya-keyboard-layout#6]
As Avro by OmicronLab is one of the most adopted Bengali Keyboard module - a add-on for the keyboard for Rokeya Keyboard will help users (and adoption). 

Same goes for Mayabi or Ridmik keyboard on android. Avro will be the fastest; also, Rokeya option in avro.im.

**Comment by MythicAngel** [comment]
Actually I do not want to provide plugin, because I just want to showcase this as a layout which is capable of generating any kind of bangla letters. Therefore, other keyboards are not part of this keyboard code.

Instead I think, a built-in spell checker will be a better option. That's the thing I can share among several other keyboard vendors. What you say?

**Comment by deathstrikex** [comment]
I think I wasn't clear about this suggestion. 

I did not suggest making other keyboard/s as a part of Rokeya, rather Rokeya being a add-on that can be added as a layout to other existing platforms (Avro being the largest to my knowledge). So people using Avro (or something else) can use Rokeya as a layout (instead of say - phonetic or probhat).

Given Rokeya as both  fixed and phonetic elements (the reason I love this, and so will a lot of people given the exposure- IMO) this add-on route (as a secondary focus) may help user adoption. 

Avro has a layout creator, initially, Rokeya can be shared as a modified layout. Though providing it as a fixed layout will be more helpful.

**Comment by MythicAngel** [comment]
Got your point. I will develop something here and send a pull-request to them.

**Comment by MythicAngel** [comment]
Cannot provide this because the addon is not actively developed and their focus is not clear also :-/
